### ISSUE TITLE
Cannot Activate Plugin

### ISSUE THREAD

**Issue by tillmanj** [ChristianGalla/PidginWinToastNotifications#10]
Plugin version 1.6.1
Pidgin Version 2.13.0

Attempts to check off the plugin in the plugin list fail.

**Comment by ChristianGalla** [comment]
Hi tillmanj,
which window version are you using?
Are there any errors in the error search window?
Are you sure, you have installed the two dll files in the correct location?
Regards
Chistian

**Comment by tillmanj** [comment]
Hi Christian,
Windows 10.0.17134
No errors in the window
double checked the files. In the correct places.

**Comment by Elberet** [comment]
Same here, the debug window is unfortunately vague and only logs that it "failed to load dll".

I'm using the same Pidgin and plugin versions as @tillmanj, my Windows is at build 17763, Win 10 Pro 1809.

**Comment by ChristianGalla** [comment]
If the error search window outputs "win_toast_notifications: failed to load dll", either the file PidginWinToastLib.dll was not copied to "C:\Program Files (x86)\Pidgin\PidginWinToastLib.dll" or there is something, that prevents the file from loading.

I have downloaded and tested the files from the newest release of my Plugin and it works on my machine.

I can think of the following:

- Windows cannot load the dll because of missing dependencies.
  Please check in Apps and Features, if you have installed "Microsoft Visual C++ 2017 Redistributable (x86)" or "Microsoft Visual C++ 2015-2019 Redistributable (x86)". If you cannot find it, please download and install it from https://aka.ms/vs/16/release/vc_redist.x86.exe.

- An antivirus software is preventing the start.
  Please check if it has logged something regarding the software or temporary disable it.

- Windows has prevented the loading of the dll.
  Please try to right click on both dll files and open the properties. Then on the general tab at the bottom there should be something about security (the file is from another computer...) and a checkbox to grant access. Please enable the checkbox.

Is something of this solving your issue?

**Comment by Elberet** [comment]
I apologize, I can no longer check if this solves the problem. I've run into more oddities / quirks / bugs with Pidgin and ended up going back to Trillian. 😥

**Comment by ChristianGalla** [comment]
@tillmanj were you able to activate the plugin?

**Comment by ChristianGalla** [comment]
Closed because issue is not reproduceable.

**Comment by brgrvrm** [comment]
I had got the same problem that cannot activate the plugin. **Solution was installing the missing "Microsoft Visual C++ 2015-2019 Redistributable (x86)".** Maybe you should note that in the Installation chapter.

**Comment by ChristianGalla** [comment]
@brgrvrm Thank you for the feedback.
I have updated the readme.
